// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaBo1krKKZ7vrfCy0CiYurLQdK0RxzIW8',
    appId: '1:829358056062:web:74d8aff13029d5c969ae2f',
    messagingSenderId: '829358056062',
    projectId: 'doan-e704b',
    authDomain: 'doan-e704b.firebaseapp.com',
    databaseURL: 'https://doan-e704b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doan-e704b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs9yNC8d3SC2uRYsjLrjT2PSbuibvrLdM',
    appId: '1:829358056062:android:ccb8be44dd3e7c1669ae2f',
    messagingSenderId: '829358056062',
    projectId: 'doan-e704b',
    databaseURL: 'https://doan-e704b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doan-e704b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuT9FcPCFOoP3eFstyQVYJYRiAbr63jQw',
    appId: '1:829358056062:ios:d3cb07970256cbd869ae2f',
    messagingSenderId: '829358056062',
    projectId: 'doan-e704b',
    databaseURL: 'https://doan-e704b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doan-e704b.firebasestorage.app',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuT9FcPCFOoP3eFstyQVYJYRiAbr63jQw',
    appId: '1:829358056062:ios:d3cb07970256cbd869ae2f',
    messagingSenderId: '829358056062',
    projectId: 'doan-e704b',
    databaseURL: 'https://doan-e704b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doan-e704b.firebasestorage.app',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaBo1krKKZ7vrfCy0CiYurLQdK0RxzIW8',
    appId: '1:829358056062:web:aeca2a30649a956069ae2f',
    messagingSenderId: '829358056062',
    projectId: 'doan-e704b',
    authDomain: 'doan-e704b.firebaseapp.com',
    databaseURL: 'https://doan-e704b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doan-e704b.firebasestorage.app',
  );
}
